# Job to create a bucket in minio
apiVersion: batch/v1
kind: Job
metadata:
  name: create-s3-bucket
spec:
  ttlSecondsAfterFinished: 360
  backoffLimit: 50
  template:
    spec:
      containers:
        - name: aws
          image: amazon/aws-cli:2.2.24
          command:
            [
              "bash",
              "-c",
              "set -o xtrace && source /minio-storage-config/config.env && export AWS_ACCESS_KEY_ID=$MINIO_ROOT_USER && export AWS_SECRET_ACCESS_KEY=$MINIO_ROOT_PASSWORD && aws s3 rb --endpoint {{ .Values.endpoint }} {{ .Values.bucketName }} --force || : && aws s3 mb --endpoint {{ .Values.endpoint }} {{ .Values.bucketName }}",
            ]
          env:
          - name: AWS_EC2_METADATA_DISABLED
            value: 'true'
          volumeMounts:
          - name: env-volume
            mountPath: /minio-storage-config
            readOnly: true
      restartPolicy: Never
      volumes:
      - name: env-volume
        secret:
          defaultMode: 0777
          secretName: {{ .Values.storageConfigSecret }}
