# MiniIO storage config. The access/secret key needs to be duplicated here
apiVersion: v1
kind: Secret
metadata:
  name: storage-configuration
stringData:
  config.env: |-
    export MINIO_ROOT_USER={{ .Values.accessKey | quote }}
    export MINIO_ROOT_PASSWORD={{ .Values.secretKey | quote }}
type: Opaque
---
# Secret to be used as MinIO Root Credentials. We use this secret as access
# credentials in v1beta1_verticadb.yaml. The accesskey/secretkey is duplicated
# in the storage-configuration.
apiVersion: v1
kind: Secret
metadata:
  name: s3-auth
type: Opaque
data:
  accesskey: {{ .Values.accessKey | b64enc }}
  secretkey: {{ .Values.secretKey | b64enc }}
