# MinIO Tenant Definition
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: minio
spec:
  configuration:
    name: {{ .Values.storageConfigSecret }}
  image: quay.io/minio/minio:RELEASE.2023-01-12T02-06-16Z
  imagePullPolicy: IfNotPresent
  pools:
    - servers: 1
      volumesPerServer: 4
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 250Mi
  mountPath: /export
  requestAutoCert: false
